CREATE DATABASE QLBH1;
GO
USE QLBH1;
GO
CREATE TABLE LOAIHANG (
    MALOAIHANG CHAR(10) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(100) NOT NULL
);
GO
CREATE TABLE MATHANG (
    MAHANG CHAR(10) PRIMARY KEY,
    TENHANG NVARCHAR(100) NOT NULL,
    MACONGTY CHAR(10),
    MALOAIHANG CHAR(10),
    SOLUONG INT CHECK (SOLUONG >= 0),
    DONVITINH VARCHAR(10) NOT NULL,
    GIAHANG MONEY NOT NULL,
    FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
);
GO

