CREATE DATABASE Tuan5_Nhom6_124TCSDL204;
USE Tuan5_Nhom6_124TCSDL204;
-- Bảng khách hàng
CREATE TABLE KHACHHANG (
    MAKHACHHANG CHAR(10) PRIMARY KEY,
    TENCONGTY NVARCHAR(50),
    TENGIAODICH NVARCHAR(50),
    DIACHI NVARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    DIENTHOAI VARCHAR(11) UNIQUE,
    FAX VARCHAR(10) UNIQUE
);
-- Bảng Nhân viên
CREATE TABLE NHANVIEN (
    MANHANVIEN INT PRIMARY KEY, 
    HO NVARCHAR(10) NOT NULL,
    TEN NVARCHAR(10) NOT NULL,
    NGAYSINH DATE NOT NULL,
    NGAYLAMVIEC DATE NOT NULL,
    DIACHI NVARCHAR(100),
    DIENTHOAI VARCHAR(11) CHECK (
        DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' 
        OR DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
    ),
    LUONGCOBAN DECIMAL(10, 2) NOT NULL,
    PHUCAP DECIMAL(10, 2)
);
-- Bảng Đơn đặt hàng
CREATE TABLE DONDATHANG (
    SOHOADON INT PRIMARY KEY, 
    MAKHACHHANG CHAR(10), -- MAKHACHHANG is CHAR(10) to match KHACHHANG
    MANHANVIEN INT,
    NGAYDATHANG DATE NOT NULL,
    NGAYGIAOHANG DATE,
    NGAYCHUYENHANG DATE,
    NOIGIAOHANG NVARCHAR(100),
    CONSTRAINT FK_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
    CONSTRAINT FK_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
);

-- Bảng nhà cung cấp
CREATE TABLE NHACUNGCAP (
    MACONGTY CHAR(10) PRIMARY KEY, 
    TENCONGTY VARCHAR(100) NOT NULL, 
    TENGIAODICH VARCHAR(100) NOT NULL, 
    DIACHI VARCHAR(255) NOT NULL, 
    DIENTHOAI VARCHAR(15) CHECK (DIENTHOAI LIKE '[0-9]+'), 
    FAX VARCHAR(20) NULL
);
-- Bảng loại hàng
CREATE TABLE LOAIHANG (
    MALOAIHANG CHAR(10) PRIMARY KEY,
    TENLOAIHANG NVARCHAR(100) NOT NULL
);
-- Bảng mặt hàng
CREATE TABLE MATHANG (
    MAHANG CHAR(10) PRIMARY KEY,
    TENHANG NVARCHAR(100) NOT NULL,
    MACONGTY CHAR(10),
    MALOAIHANG CHAR(10),
    SOLUONG INT CHECK (SOLUONG >= 0),
    DONVITINH VARCHAR(10) NOT NULL,
    GIAHANG MONEY NOT NULL,
    FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
    FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
);
-- Bảng chi tiết đã đặt
CREATE TABLE CHITIETDADAT (
    SOHOADON INT, 
    MAHANG CHAR(10), 
    GIABAN INT NOT NULL, 
    SOLUONG INT NOT NULL, 
    MUCGIAMGIA DECIMAL(10, 2) CHECK (MUCGIAMGIA >= 0 AND MUCGIAMGIA <= 100),
    PRIMARY KEY (SOHOADON, MAHANG), 
    FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
    FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
);
