CREATE DATABASE Tuan5_Nhom6;
go
use Tuan5_Nhom6;
--Bảng Đơn đặt hàng 
CREATE TABLE DONDATHANG (
	SOHOADON INT PRIMARY KEY, 
	MAKHACHHANG	INT,
	MANHANVIEN INT,
	NGAYDATHANG	DATE NOT NULL,
	NGAYGIAOHANG DATE,
	NGAYCHUYENHANG DATE,
	NOIGIAOHANG	NVARCHAR(100),
	CONSTRAINT FK_DONDATHANG_NHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN),
	CONSTRAINT FK_DONDATHANG_KHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)
);  
--Bảng Nhân viên 
CREATE TABLE NHANVIEN(
	MANHANVIEN INT PRIMARY KEY, 
	HO NVARCHAR(10)	NOT NULL,
	TEN	NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYLAMVIEC	DATE NOT NULL,
	DIACHI NVARCHAR(100),
	DIENTHOAI VARCHAR(11) CHECK (
		DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
		DIENTHOAI LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	LUONGCOBAN DECIMAL (10,2) NOT NULL,
	PHUCAP DECIMAL (10,2),
);